### ISSUE TITLE
Confusion with continuous action space (`DiagGaussian`)

### ISSUE THREAD

**Issue by KeirSimmons** [ikostrikov/pytorch-a2c-ppo-acktr-gail#109]
My action space is as such: `Box(np.array([0]), np.array([0.1]))`

Using a `Box` automatically makes the agent model the action space using the `DiagGaussian` distribution. However, the actions sampled from this distribution do not lie within `[0, 0.1]`. Can you please explain how to interpret this, and how to effectively use the correct action from the sampled value?

**Comment by timmeinhardt** [comment]
I am not very familiar with non-discrete action spaces but in general your policy model is not aware of the range specified in the action space. In the case of a continuous action space our policy model implements a Gaussian distribution to sample values as actions. As far as I know, the mapping to your specific range is then usually done in the `step` method of your environment. See for example the [continuous mountain car](https://github.com/openai/gym/blob/master/gym/envs/classic_control/continuous_mountain_car.py) where they clip the action value.

**Comment by rwightman** [comment]
I'm not sure if you've noticed, but there is a similar and more extensive conversation on this clip/scale in the environment vs handle in the model topic at https://github.com/openai/baselines/issues/121

**Comment by ikostrikov** [comment]
I would say the right way to handle this is to apply tanh and handle probabilities properly:

See Appendix C:
https://arxiv.org/pdf/1801.01290.pdf

**Comment by wranai** [comment]
Somebody mentioned on the thread @rwightman referenced to use the beta distribution, i.e. return not a mean/stddev pair for a normal distribution but the two parameters for a beta distribution (then transform the 0..1 range to between the Box limits). I guess the best way to return the params would be in the -inf..inf range, and then apply softplus to constrain them to be positive. 1 is a special value for the beta parameters so that's why I would go with softplus and not exp.
