### ISSUE TITLE
General questions regarding recurrent policy

### ISSUE THREAD

**Issue by DaStapo** [ikostrikov/pytorch-a2c-ppo-acktr-gail#234]
1. Does using recurrent policy mean that it will use a sliding window of observation sequences of the size `num_steps` as inputs?
2. Why is there a requirement for `num_processes >= num_mini_batch`? My machine fails to run more than 12 proccesses and I'm worried a small mini batch size would affect the results.

**Comment by Xemnas0** [comment]
I am interested in this answer as well

**Comment by erikwijmans** [comment]
1. No, the recurrent policy doesn't use a sliding window, it uses a recurrent neural network.  In the normal policy, the action at time t `a_t` is just a function current observation `o_t`, i.e. `a_t = f(o_t)`, in a recurrent policy, there is an additional input/output of the policy that allows information to be carried between time-steps, i,e `a_t, h_t = f(o_t, h_{t-1})`.  `num_steps` still has the same function as normal (determines the rollout length), but now also kinda functions like the truncation length in truncated backprop through time.

2. The requirement for `num_processes >= num_mini_batch` is because the recurrent policy needs to be given sequences to be correctly updated.  Note that you have `num_mini_batch` backwards.  Increasing `num_mini_batch` decreases the batch size.  Batch size is ` num_steps * num_processes / num_mini_batch`.
